name: system-design
version: 0.1.0.0
github: "gmatiukhin/system-design"
license: BSD-3-Clause
author: "Grigorii Matiukhin"
maintainer: "contact@gmatiukhin.site"
copyright: "2024 Grigorii Matiukhin"
extra-source-files:
  - README.md
# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/gmatiukhin/system-design#readme>
dependencies:
  - base >= 4.7 && < 5
  - Chart == 1.9.5
  - Chart-diagrams == 1.9.5.1
  - regex-posix == 0.96.0.1
  - directory
  - containers
  - text
ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
executables:
  lab1-exe:
    main: lab1.lhs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
  lab2-exe:
    main: lab2.lhs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
  lab3-exe:
    main: lab3.lhs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
  lab4-exe:
    main: lab4.lhs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
